# This is a basic workflow to help you get started with Actions

name: Run shell commands

# Controls when the workflow will run - Change1
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
 
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
        - name: Echo a String
          run: echo "Hello World, this is my first Github Actions file"
  
