# This is a basic workflow to help you get started with Actions

name: Run shell commands

# Below controls when the workflow will run
on:
  # Triggers the workflow on push request event but only for the "main" branch
  push:
    branches: ["main"]

jobs:
  run-shell-command:                              # Action which is used to run shell commands
    runs-on: ubuntu-latest                        # Specify on which server this will run : Ubuntu
    steps:                                        # Specify steps that it will perform
      - name: Echo a String                       # Name is a command basically it states which command you want to run
        run: echo "Hello World, this is my first Github Actions file"       # Run is a command basically it will be executed
